name: CI

on:
  push:
    branches: [main, beta, alpha]
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:
  lint-and-test:
    name: Linting and testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '18.x'
      - name: install dependencies
        run: yarn --frozen-lockfile
      - name: lint and test
        uses: mansagroup/nrwl-nx-action@v2
        with:
          targets: lint,test
          maxParallel: 3

  release:
    name: Building and releasing project
    runs-on: ubuntu-latest
    needs: [lint-and-test]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '18.x'
      - name: install dependencies
        run: yarn --frozen-lockfile
      - name: build and release
        run: yarn nx run-many --all --target=version --parallel=false
        env:
          CI: true
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
          NPM_TOKEN: ${{ secrets.ASSOCIATION_NPM_TOKEN }}

  check-fast-forward:
    name: Check if fast forwarding is possible
    runs-on: ubuntu-latest
    needs: [lint-and-test]
    if: github.event_name == 'pull_request'

    permissions:
      contents: read
      # We appear to need write permission for both pull-requests and
      # issues in order to post a comment to a pull request.
      pull-requests: write
      issues: write

    steps:
      - name: Checking if fast forwarding is possible
        uses: sequoia-pgp/fast-forward@v1
        with:
          merge: false
          # To reduce the workflow's verbosity, use 'on-error'
          # to only post a comment when an error occurs, or 'never' to
          # never post a comment.  (In all cases the information is
          # still available in the step's summary.)
          comment: never
