name: CI

on:
  push:
    branches: [main, beta, alpha]
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:
  lint-and-test:
    name: Linting and testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: install dependencies
        run: yarn --frozen-lockfile
      - name: lint and test
        uses: mansagroup/nrwl-nx-action@v2
        with:
          targets: lint,test
          maxParallel: 3

  release:
    name: Building and releasing project
    runs-on: ubuntu-latest
    needs: [lint-and-test]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: install dependencies
        run: yarn --frozen-lockfile
      - name: build and release
        run: yarn nx run-many --all --target=release --parallel=1
        env:
          CI: true
          GITHUB_TOKEN: ${{ secrets.JERE_RELEASE_TOKEN }}
          NPM_TOKEN: ${{ secrets.ASSOCIATION_NPM_TOKEN }}
